In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import roc_auc_score

In [50]:
data=pd.read_csv(r"path")

In [51]:
data.shape

(300000, 51)

In [52]:
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V42,V43,V44,V45,V46,V47,V48,V49,V50,Subscribers
0,-0.211875,743952.92,743952.92,200000.0,743952.92,200000.000,200000.0,-0.069396,943952.92,0.00,...,1.034232e+06,1966.57,1990.82,1752.89,100000.0,147.0,1826.046667,28.0,2557.22,0
1,0.241488,11295310.87,8034290.99,32000.0,8034290.99,18000.000,14000.0,0.167411,7508345.76,1160925.13,...,5.665658e+07,49957.65,11104.54,17711.99,38000.0,19.0,26467.683330,19.0,12807.07,0
2,0.459032,20363.68,317922.94,1650000.0,317922.94,1650000.000,1650000.0,46.068404,1655168.31,0.00,...,2.654720e+04,453.96,9.64,58.83,45072.0,0.0,315.506667,0.0,32.12,1
3,0.000000,856120.91,856120.91,0.0,856120.91,45554.885,0.0,0.000000,856120.91,0.00,...,8.506973e+05,2045.09,2045.09,2011.19,45072.0,30.0,2045.090000,19.0,2029.79,0
4,8.270783,194485.64,412330.33,835000.0,412330.33,835000.000,835000.0,-0.272225,2241.64,78625.00,...,5.572559e+04,70.01,100.60,89.59,31080.0,0.0,294.580000,0.0,26.95,0

In [53]:
y=pd.get_dummies(data['Subscribers'])

In [54]:
y

        0  1
0       1  0
1       1  0
2       0  1
3       1  0
4       1  0
...    .. ..
299995  1  0
299996  1  0
299997  1  0
299998  1  0
299999  0  1

[300000 rows x 2 columns]

In [55]:
x=data.drop(['Subscribers'],axis=1)

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,
                                               random_state=2)

In [57]:
x_train

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V41,V42,V43,V44,V45,V46,V47,V48,V49,V50
18736,-0.629091,228317.55,117202.89,0.00,117202.89,0.000,0.0,-0.301283,23762.55,121000.00,...,0,9.185869e+04,660.10,1059.93,97.01,383700.00,10.0,663.866667,10.0,98.30
147527,0.000000,179586.61,179586.61,0.00,179586.61,45554.885,0.0,0.000000,179586.61,0.00,...,0,2.687630e+05,449.40,449.40,442.29,45072.00,30.0,449.400000,19.0,449.40
1729,-0.108635,107500.00,106724.14,0.00,106724.14,0.000,0.0,0.129023,162916.00,48030.00,...,0,1.335116e+06,1312.09,1289.69,1226.95,0.00,32.0,1327.910000,32.0,1254.93
189132,0.344743,581827.88,581810.16,0.00,581810.16,45554.885,0.0,-0.015048,455474.60,0.00,...,0,5.749499e+05,988.01,1006.81,1032.64,45072.00,0.0,1044.460000,0.0,1040.95
280431,0.531380,250918.54,149340.88,141979.55,149340.88,138979.550,74992.0,-0.109655,175804.51,73945.61,...,2,2.777495e+05,2084.53,417.05,230.61,108869.51,4.0,963.563333,0.0,178.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33867,0.013980,190788.69,282149.59,300000.00,282149.59,300000.000,0.0,0.788668,252215.69,404485.80,...,0,7.354559e+05,995.99,1567.45,1086.62,113334.00,135.0,1373.640000,53.0,942.90
84434,0.036289,153162.20,142944.78,23798.80,142944.78,23798.800,6460.0,0.035871,154403.45,10376.19,...,2,2.966229e+05,397.49,531.77,383.30,8885.50,0.0,704.186667,0.0,206.02
95816,-0.469078,566118.15,76905.23,85000.00,76905.23,85000.000,60000.0,0.266498,474668.90,71021.00,...,1,2.735930e+07,23151.09,22652.13,22798.06,323773.00,0.0,23254.696670,7.0,22931.90
203245,0.036412,286019.00,282964.79,1000.00,282964.79,1000.000,0.0,0.037845,277007.00,0.00,...,0,3.200851e+05,641.69,620.95,505.23,0.00,129.0,641.680000,129.0,546.92
100879,0.035484,329115.32,329115.32,0.00,329115.32,45554.885,0.0,-0.060706,313834.32,0.00,...,0,3.557193e+05,782.58,825.37,847.99,45072.00,30.0,804.676667,342.0,866.38

In [58]:
x_train.reset_index(drop=True,inplace=True)
y_train.reset_index(drop=True,inplace=True)

In [59]:
st=StandardScaler()

In [60]:
st.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [61]:
x_train=pd.DataFrame(st.transform(x_train))
x_test=pd.DataFrame(st.transform(x_test))

In [62]:
x_train.shape

(240000, 50)

# simple logistic regression with zero hidden layers

In [63]:
weights = tf.Variable(tf.random.normal(shape=(50, 2), dtype=tf.float64))
biases  = tf.Variable(tf.random.normal(shape=(2,), dtype=tf.float64))

In [64]:
def logistic_regression(x):
    lr = tf.add(tf.matmul(x, weights), biases)
    return lr


def cross_entropy(y_true, y_pred):
    loss = tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y_pred)
    return tf.reduce_mean(loss)

def accuracy(y_true, y_pred):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32)
    preds = tf.cast(tf.argmax(y_pred, axis=1), dtype=tf.int32)
    preds = tf.equal(y_true, preds)
    return tf.reduce_mean(tf.cast(preds, dtype=tf.float32))

def roc_auc(y_true,x):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32).numpy()
    y_pred=tf.nn.softmax(logistic_regression(x))[:,1]
    return(roc_auc_score(y_true,y_pred))

def grad(x, y):
    with tf.GradientTape() as tape:
        y_pred = logistic_regression(x)
        loss_val = cross_entropy(y, y_pred)
    return tape.gradient(loss_val, [weights, biases])

In [65]:
epochs=2000

In [66]:
y_true=tf.cast(tf.argmax(y_test.values,axis=1),dtype=tf.int32)

In [67]:
preds=tf.cast(tf.argmax(logistic_regression(x_test.values),axis=1),dtype=tf.int32)

In [68]:
tf.reduce_mean(tf.cast(tf.equal(y_true,preds),dtype=tf.float32))

In [69]:
learning_rate=0.01
for epoch in range(epochs):
    rand_ind=np.random.choice(range(x_train.shape[0]),100)
    outputs=y_train.iloc[rand_ind,:].values
    inputs=x_train.iloc[rand_ind,:].values
    
    dw,db=grad(inputs,tf.cast(outputs,'float32'))
    
    weights.assign_sub(learning_rate*dw)
    biases.assign_sub(learning_rate*db)
    
    if epoch%50==0:
        
        print(accuracy(y_test.values,logistic_regression(x_test.values)).numpy(),roc_auc(y_test.values,x_test.values))

0.33498332 0.4018654189261258
0.35336667 0.40340710690092435
0.37258333 0.4051749348627043
0.39876667 0.40891005205552183
0.42921665 0.41231596207746585
0.46836665 0.4174091696044256
0.5169167 0.42476890369144277
0.5776 0.4318316677985373
0.6491333 0.4438942619667911
0.717 0.45602413906009753
0.76705 0.46573833006458637
0.7946 0.4757784918213543
0.8068333 0.4849381191294171
0.81186664 0.49549898576326723
0.81505 0.5009369856775984
0.8156667 0.5137412198689039
0.81715 0.5198256262597952
0.81745 0.5249357514738121
0.818 0.5320161307635496
0.81865 0.5385835733623395
0.81905 0.5423758363489826
0.8196 0.5471765792876759
0.8197167 0.55239000125346
0.8199667 0.556608013005913
0.81986666 0.5617286875964473
0.82015 0.565319064686319
0.82015 0.5695626551844644
0.8203 0.573804407185841
0.82055 0.5764264767480097
0.8207167 0.5801219998321477
0.8210667 0.5824714951528668
0.82093334 0.5863011190900526
0.82115 0.5889182846916584
0.82158333 0.5916715303144593
0.82191664 0.59348402046209
0.822 0.5967386149710188
0.8221 0.5988343977376479
0.82243335 0.599083511119162
0.8225167 0.6002056945743495
0.82236665 0.603356039869051

# classfier with a hidden layer

In [70]:
weights_h = tf.Variable(tf.random.truncated_normal(shape=(50, 20), dtype=tf.float64))
biases_h  = tf.Variable(tf.random.truncated_normal(shape=(20,), dtype=tf.float64))

weights_o = tf.Variable(tf.random.truncated_normal(shape=(20, 2), dtype=tf.float64))
biases_o  = tf.Variable(tf.random.truncated_normal(shape=(2,), dtype=tf.float64))

In [71]:
def logistic_regression(x):
    h_o = tf.add(tf.matmul(x, weights_h), biases_h)
    h_o=tf.nn.relu(h_o)
    lr=tf.add(tf.matmul(h_o, weights_o), biases_o)
    return lr


def cross_entropy(y_true, y_pred):

    loss = tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y_pred)
    return tf.reduce_mean(loss)


def accuracy(y_true, y_pred):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32)
    preds = tf.cast(tf.argmax(y_pred, axis=1), dtype=tf.int32)
    preds = tf.equal(y_true, preds)
    return tf.reduce_mean(tf.cast(preds, dtype=tf.float32))

def roc_auc(y_true,x):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32).numpy()
    y_pred=tf.nn.softmax(logistic_regression(x))[:,1]
    return(roc_auc_score(y_true,y_pred))

def grad(x, y):
    with tf.GradientTape() as tape:
        y_pred = logistic_regression(x)
        loss_val = cross_entropy(y, y_pred)
    return tape.gradient(loss_val, [weights_h, biases_h,weights_o, biases_o])

In [72]:
epochs=2000

In [73]:
learning_rate=0.01
for epoch in range(epochs):
    rand_ind=np.random.choice(range(x_train.shape[0]),100)
    outputs=y_train.iloc[rand_ind,:].values
    inputs=x_train.iloc[rand_ind,:].values
    
    dw_h,db_h,dw_o,db_o=grad(inputs,tf.cast(outputs,'float32'))
    
    weights_h.assign_sub(learning_rate*dw_h)
    biases_h.assign_sub(learning_rate*db_h)
    weights_o.assign_sub(learning_rate*dw_o)
    biases_o.assign_sub(learning_rate*db_o)
    
    if epoch%50==0:
        print(accuracy(y_test.values,logistic_regression(x_test.values)).numpy(),roc_auc(y_test.values,x_test.values))

0.2533 0.43285945196665976
0.70211667 0.4923988552663367
0.75908333 0.5160329305132859
0.77848333 0.531228589865007
0.7856333 0.5409189497703067
0.7953167 0.5489109860744009
0.8010833 0.5584307448114203
0.80215 0.5633209694002317
0.80576664 0.5672680949677791
0.8075167 0.5684752537045438
0.7912667 0.5762723634375736
0.8074167 0.5830530931530011
0.81215 0.5833661406992472
0.8138 0.5878898391726791
0.8178833 0.5885064115943414
0.81691664 0.5873202900668837
0.8185833 0.5875631474795843
0.80413336 0.5999025301693413
0.8171167 0.6036028556180464
0.8174833 0.6084018811936583
0.82065 0.6084907014929196
0.8135833 0.6140085402297363
0.8171833 0.6132640066745756
0.8181667 0.6129919111065673
0.82313335 0.6117866895319136
0.81986666 0.6180391337459625
0.8193833 0.6185294262524788
0.81956667 0.6189515263544038
0.82336664 0.6171515911273215
0.82498336 0.6158159417856195
0.82166666 0.6222567527908165
0.82626665 0.6138753957466868
0.82556665 0.6164145786064982
0.8256 0.619202863125209
0.8246167 0.6184091932528474
0.8254 0.6180870684951373
0.8257333 0.6222432463846929
0.8261833 0.6251755979328779
0.82535 0.6263870051406558
0.82533336 0.6276927911209227